project:
  type: website
  output-dir: docs

website:
  title: ""

format:
  html:
    theme: none
    toc: false
    page-layout: full
    anchor-sections: false
    smooth-scroll: true
    include-in-header:
      - text: |
          <meta name="viewport" content="width=device-width, initial-scale=1">
